title: Emely Pineda | Data Analytics Portfolio
theme: jekyll-theme-slate

sass:
  style: compressed

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

nav:
  - title: "ğŸ” Project Overview"
    url: "/bellabeat.html#project-overview"
  - title: "ğŸ§¹ Excel Cleaning"
    url: "/bellabeat.html#excel-cleaning"
  - title: "ğŸ§® SQL Queries in BigQuery"
    url: "/bellabeat.html#sql-queries"
  - title: "ğŸ–¥ï¸ RStudio Analysis"
    url: "/bellabeat.html#rstudio-analysis"
  - title: "ğŸ’¡ Key Insights"
    url: "/bellabeat.html#key-insights"
  - title: "ğŸ¤ Acknowledgements"
    url: "/bellabeat.html#acknowledgements"


