title: Emely Pineda | Data Analytics Portfolio
theme: jekyll-theme-slate

sass:
  style: compressed

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

nav:
  - title: "ğŸ” Project Overview"
    url: "/bellabeat.html#project-overview"
    subnav:
      - title: "The Data"
        url: "/bellabeat.html#the-data"
  - title: "ğŸ§® SQL Queries in BigQuery"
    url: "/bellabeat.html#sql-queries"
    subnav:
      - title: "Hourly Data"
        url: "/bellabeat.html#hourly-data-sql"
      - title: "Daily/Sleep Data"
        url: "/bellabeat.html#daily-sleep-data-sql"
  - title: "ğŸ–¥ï¸ RStudio Analysis"
    url: "/bellabeat.html#rstudio-analysis"
    subnav:
      - title: "Hourly Data"
        url: "/bellabeat.html#hourly-data-r"
      - title: "Daily/Sleep Data"
        url: "/bellabeat.html#daily-sleep-data-r"
  - title: "ğŸ’¡ Key Insights"
    url: "/bellabeat.html#key-insights"
    subnav:
      - title: "Proposal"
        url: "/bellabeat.html#proposal"
  - title: "ğŸ¤ Acknowledgements"
    url: "/bellabeat.html#acknowledgements"



