title: Emely Pineda | Data Analytics Portfolio
theme: mediumish

sass:
  style: compressed

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

nav:
  - title: "ğŸ” Project Overview"
    url: "/bellabeat.html#project-overview"
  - title: "The Data"
    url: "/bellabeat.html#the-data"
  - title: "ğŸ§® SQL Queries in BigQuery"
    url: "/bellabeat.html#sql-queries"
  - title: "Hourly Data (SQL)"
    url: "/bellabeat.html#hourly-data-sql"
  - title: "Daily/Sleep Data (SQL)"
    url: "/bellabeat.html#daily-sleep-data-sql"
  - title: "ğŸ–¥ï¸ RStudio Analysis"
    url: "/bellabeat.html#rstudio-analysis"
  - title: "Hourly Data (R)"
    url: "/bellabeat.html#hourly-data-r"
  - title: "Daily/Sleep Data (R)"
    url: "/bellabeat.html#daily-sleep-data-r"
  - title: "ğŸ’¡ Key Insights"
    url: "/bellabeat.html#key-insights"
  - title: "Proposal"
    url: "/bellabeat.html#proposal"
  - title: "ğŸ¤ Acknowledgements"
    url: "/bellabeat.html#acknowledgements"
